---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - batch.kostis.test.eu
  resources:
  - hellojobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.kostis.test.eu
  resources:
  - hellojobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch.kostis.test.eu
  resources:
  - hellojobs/status
  verbs:
  - get
  - patch
  - update
